version: 2.1

jobs:
  validate_template:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install tar gzip -y
      - run:
          name: Validate eks template
          command: |
            aws cloudformation validate-template --template-body file://eks-create-template.yml
  # deploy-infrastructure:
  #   docker:
  #     # Docker image here that supports AWS CLI
  #     - image: amazon/aws-cli
  #   steps:
  #     # Checkout code from git
  #     - checkout
  #     - run: yum install tar gzip -y
  #         name: Ensure eks deployment is successful
  #         command: |
  #           aws cloudformation deploy \
  #              --template-file .circleci/eks-create-template.yml \
  #              --tags project=eks_deploy \
  #              --s3-bucket eks_deploys \
  #              --stack-name "eks_deploy-${CIRCLE_WORKFLOW_ID:0:7}" \
  #              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"      
  #     - destroy-environment:
  #         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
workflows:
  default:
    jobs:
      - validate_template
      # - deploy-infrastructure